var adimlar = [
    ".",
    ".a",
    ".an",
    ".ana",
    ".anak",
    ".anako",
    ".anakom",
    ".anakomu ",
    ".anakomut",
    ".anakomutl",
    ".anakomutla",
    ".anakomutlar",
    ".anakomutlar",
    ".anakomutlar",
    ".anakomutlar",
    ".anakomutla",
    ".anakomutl",
    ".anakomut",
    ".anakomu",
    ".anakom",
    ".anako",
    ".anak",
    ".ana",
    ".an",
    ".a",
    ".",
    ".c",
    ".ca",
    ".can",
    ".canl",
    ".canlı",
    ".canlıd",
    ".canlıde",
    ".canlıdes",
    ".canlıdest",
    ".canlıdeste",
    ".canlıdestek",
    ".canlıdestek",
    ".canlıdestek",
    ".canlıdestek",
    ".canlıdeste",
    ".canlıdest ",
    ".canlıdes",
    ".canlıde",
    ".canlıd",
    ".canlı",
    ".canl",
    ".can",
    ".ca",
    ".c",
    ".",
    ".y",
    ".yo",
    ".you",
    ".yout",
    ".youtu",
    ".youtub",
    ".youtube",
    ".youtube",
    ".youtube",
    ".youtube",
    ".youtub",
    ".youtu",
    ".yout",
    ".you",
    ".yo",
    ".y",
    ".",
    ".s",
    ".su",
    ".sun",
    ".sunu",
    ".sunuc",
    ".sunucu",
    ".sunucuk",
    ".sunucuku",
    ".sunucukur",
    ".sunucukur",
    ".sunucukur",
    ".sunucukur",
    ".sunucuku",
    ".sunucuk",
    ".sunucu",
    ".sunuc",
    ".sunu",
    ".sun",
    ".su",
    ".s",
    ".",
    ".i",
    ".is",
    ".isi",
    ".isim",
    ".isimd",
    ".isimde",
    ".isimdeğ",
    ".isimdeği",
    ".isimdeğiş",
    ".isimdeğişt",
    ".isimdeğişti",
    ".isimdeğiştir",
    ".isimdeğiştir",
    ".isimdeğiştir",
    ".isimdeğiştir",
    ".isimdeğişti",
    ".isimdeğişt",
    ".isimdeğiş",
    ".isimdeği",
    ".isimdeğ",
    ".isimde",
    ".isimd",
    ".isim",
    ".isi",
    ".is",
    ".i",
    ".",
    "o!ekşi p",
    "o!ekşi ",
    "o!ekşi",
    "o!ekş",
    "o!ek",
    "o!e",
    "o!",
    "o!o",
    "o!oy",
    "o!oyl",
    "o!oyla",
    "o!oylam",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylam",
    "o!oyla",
    "o!oyl",
    "o!oy",
    "o!o",
    "",
  "",
  "",
  "",
  "".
  

  
  
  
  
var = 0, ntvar ocument.getElementById("command");
setInterval(() => {
    element.innerText = adimlar[x];
    if (x == adimlar.length - 1) {
        x = 0;
    } else {
        x += 1;
    }
}, 100)